### ISSUE TITLE
Could not retrieve warranty_end: can't convert String into Integer

### ISSUE THREAD

**Issue by Shiekron** [camptocamp/puppet-dell#41]
Getting this on some boxes, not too sure why:

Could not retrieve warranty_end: can't convert String into Integer
Could not retrieve warranty_end: can't convert String into Integer
Could not retrieve warranty_end: can't convert String into Integer
Could not retrieve warranty_end: can't convert String into Integer
Could not retrieve warranty_days_left: can't dup NilClass
Could not retrieve warranty_end: can't convert String into Integer
Could not retrieve warranty_end: can't convert String into Integer
Could not retrieve warranty_days_left: can't dup NilClass

Although it does get the start_date?

Here is the json it created:

{
  "GetAssetWarrantyResponse": {
    "GetAssetWarrantyResult": {
      "Response": {
        "DellAsset": {
          "ShipDate": "2011-03-16T05:00:00",
          "LocalChannel": "05",
          "OrderNumber": 622771835,
          "ItemClassCode": "7X002",
          "Warranties": {
            "Warranty": {
              "ServiceLevelDescription": "Next Business Day Onsite",
              "ServiceLevelGroup": 5,
              "ItemNumber": "909-2073",
              "ServiceLevelCode": "ND",
              "StartDate": "2012-03-17T05:00:00",
              "ServiceProvider": "QLX",
              "EntitlementType": "EXTENDED",
              "EndDate": "2015-03-17T04:59:59"
            }
          },
          "ParentServiceTag": {
            "@nil": "true"
          },
          "MachineDescription": "PowerEdge R310",
          "IsDuplicate": "false",
          "CountryLookupCode": 11,
          "CustomerNumber": 7748807,
          "AssetParts": {
            "@nil": "true"
          },
          "ServiceTag": "38RQCP1"
        }
      },
      "@i": "http://www.w3.org/2001/XMLSchema-instance",
      "@a": "http://schemas.datacontract.org/2004/07/Dell.AWR.Domain.Asset",
      "Faults": null
    },
    "@xmlns": "http://tempuri.org/"
  }
}

But somehow can't get the startdate, but does get the enddate ?

What could be the issue?

**Comment by raphink** [comment]
Closing as bug is *ancient*. Please reopen if this is still reproduceable.
