### ISSUE TITLE
Dell repository deprecated

### ISSUE THREAD

**Issue by jschaeff** [camptocamp/puppet-dell#67]
They say the linux repository is deprectated.
http://linux.dell.com/repo/hardware/Linux_Repository_15.07.00/

We have to switch to Dell System Update: http://linux.dell.com/repo/hardware/

Now, yum complains there is no more mirror available. I guess this problem only happens if the packages are not installed yet:

>   srvadmin-isvc-8.3.0-1908.9058.el6.x86_64: failure: srvadmin/srvadmin-isvc-8.3.0-1908.9058.el6.x86_64.rpm from dell-omsa-specific: [Errno 256] No more mirrors to try.

**Comment by ckaenzig** [comment]
Fixed in #72 + #74
