### ISSUE TITLE
warranty check check_dell_warranty no gitorious.org

### ISSUE THREAD

**Issue by NissesSenap** [camptocamp/puppet-dell#69]
Hi im currently looking at your puppet module to see if this something that i could use.
I think the warranty seems rather nifty but when look at the 
class dell::warranty (
  $ensure = present,
  $git_remote = 'https://git.gitorious.org/smarmy/check_dell_warranty.git',
) {
From what i can see gitorious.org isn't available any more, i found two check_dell_warranty in github but since i don't know how the old script looked like i can't send in a pull request to fix it.

Please look in to this.

**Comment by raphink** [comment]
This code was changed a long time ago, so this issue does not apply anymore.
